const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Google",
    location: "Remote",
    type: "fulltime",
    workMode: "remote",
    experience: "1-2",
    skills: ["React", "CSS", "JavaScript"],
    education: "bachelor",
    salary: "$80,000 - $100,000",
  },
  {
    id: 2,
    title: "Backend Developer",
    company: "Amazon",
    location: "New York",
    type: "fulltime",
    workMode: "onSite",
    experience: "2-3",
    skills: ["Node.js", "MongoDB", "Express"],
    education: "bachelor",
    salary: "$90,000 - $120,000",
  },
  {
    id: 3,
    title: "UI/UX Designer",
    company: "Apple",
    location: "Remote",
    type: "contract",
    workMode: "remote",
    experience: "1-2",
    skills: ["Figma", "CSS", "Design"],
    education: "diploma",
    salary: "$70,000 - $90,000",
  },
  {
    id: 4,
    title: "React Intern",
    company: "Startup Inc",
    location: "Hybrid",
    type: "internship",
    workMode: "hybrid",
    experience: "fresher",
    skills: ["React", "JavaScript"],
    education: "bachelor",
    salary: "$20,000 - $30,000",
  },
  {
    id: 5,
    title: "Data Scientist",
    company: "Microsoft",
    location: "Remote",
    type: "fulltime",
    workMode: "remote",
    experience: "2-3",
    skills: ["Python", "ML", "Data"],
    education: "master",
    salary: "$100,000 - $130,000",
  },
  {
    id: 6,
    title: "DevOps Engineer",
    company: "Netflix",
    location: "Remote",
    type: "fulltime",
    workMode: "remote",
    experience: "5+",
    skills: ["Docker", "AWS", "Linux"],
    education: "bachelor",
    salary: "$120,000 - $150,000",
  },
  {
    id: 7,
    title: "Mobile Developer",
    company: "Uber",
    location: "Hybrid",
    type: "fulltime",
    workMode: "hybrid",
    experience: "1-2",
    skills: ["React Native", "JavaScript"],
    education: "bachelor",
    salary: "$85,000 - $110,000",
  },
  {
    id: 8,
    title: "Python Intern",
    company: "Meta",
    location: "Remote",
    type: "internship",
    workMode: "remote",
    experience: "fresher",
    skills: ["Python", "Django"],
    education: "higherSecondary",
    salary: "$15,000 - $25,000",
  },
];

export default jobs;
